version: $(APPVEYOR_REPO_TAG_NAME).{build}
image: Visual Studio 2019
configuration: Release
platform:
- Win32
- x64
shallow_clone: true

before_build:
- cmd: >-
    beforebuild.bat

build:
  project: bld-vs2015\EngineToolset_vs2015.sln
  verbosity: minimal

after_build:
- cmd: >-
    afterbuild.bat

artifacts:
- path: .\dist\xray_re-tools_$(appveyor_repo_tag_name)_$(cor_plat).7z
  name: release

deploy:
- provider: GitHub
  auth_token:
    secure: pXJeBrB1oq+/lPsy2jphy4dRQ542dkJRbAEOD3y/YgSVsoRTSgIt01EI92q9whrl
  artifact: release
  on:
    appveyor_repo_tag: true